### ISSUE TITLE
Brave

### ISSUE THREAD

**Issue by Chainomics** [cifunibas/cifBlockchainMarketStudy#50]

**Comment by joschicif** [comment]
I just finished my summary of Brave before I noticed that you had created a separate issue for the Basic Attention Token. The problem is that I wrote about both projects in the same file. From my point of view it doesn't really make sense to treat them separately because, if I got it right, Brave is only a web browser and has nothing to do with blockchain. They launched the Basic Attention Token to be included into their browser as a medium of exchange between users, advertisers and publishers. What do you think about the proposal of treating them as one project?

**Comment by Chainomics** [comment]
That's fine. Didn't realize it's the same organization behind the two projects.
